
oc_core_home:
    path:      /
    defaults:  { _controller: OCCoreBundle:Core:index }

oc_core_contact:
    path:      /contact
    defaults:  { _controller: OCCoreBundle:Core:contact }

oc_core_purge:
    path:      /platform/purge/{days}/{readonly}
    defaults:  { _controller: OCCoreBundle:Core:purge, readonly: 1 }
